movie/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from movie.forms import UserLoginForms
from movie.models import User, db
from movie.models import User,db, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForms()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            firstname = form.firstname.data
            lastname = form.lastname.data
            email = form.email.data
            password = form.password.data
            username = form.username.data
            date_of_birth = form.date_of_birth.data
            print(email, username)

            user = User(firstname=firstname, lastname=lastname, email=email,
                        password=password, username=username, date_of_birth=date_of_birth)
            db.session.add(user)
            db.session.commit()

            flash(
                f'You have successfully created a user account {username}', 'user-created')

            return redirect(url_for('auth.signin'))

    except:
        raise Exception("Invalid form data. Please check your form")

    return render_template('signup.html', form=form)



@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForms()    
    try:
        if request.method == 'POST':
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            print(logged_user)
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in: Via Email/Password', 'auth-success')
                return redirect(url_for('site.watchlist'))
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

movie/site/routes.py
from flask import Blueprint, render_template, redirect, request, url_for
from flask_login import login_required, current_user
from movie.forms import MovieForm
from movie.models import db, Movie
import requests

site = Blueprint('site',__name__,template_folder='site_templates')



@site.route('/')
def home():
    #print("ooga booga in the terminal")
    return render_template('index.html')


@site.route('/search', methods=['GET', 'POST'])
@login_required
def search_movies():
    if request.method == 'POST':
        # Get the search query from the form
        query = request.form.get('search_query')
        
        # Make a request to the movie API
        url = "https://ott-details.p.rapidapi.com/search"

        querystring = {"title":query,"page":"1"}

        headers = {
            "X-RapidAPI-Key": "780cf98630mshc62147f8861e21dp1c4da7jsnce244a655e2a",
            "X-RapidAPI-Host": "ott-details.p.rapidapi.com"
        }

        response = requests.get(url, headers=headers, params=querystring)
                
        data = response.json()
        print("Data= ", data)

        # Extract the relevant details from the API response
        movies = []
        if 'results' in data:
            for movie_data in data['results']:
                title = movie_data['title']
                imdb_id = movie_data['imdbid']
                release_year = movie_data['released']
                genre = movie_data['genre']
                m_type = movie_data['type']
                image_url = movie_data.get('imageurl')
                movies.append((title, imdb_id, release_year, genre, m_type, image_url))

        print("Movie: ", movies)
        return render_template('profile.html', movies_watch=movies)
    
    return render_template('profile.html')

@site.route('/addtowatchlist', methods=['GET', 'POST'])
@login_required
def add_to_watchlist():
    if request.method == 'POST':
        try:
            title = request.form.get('movie_title')
            imdb_id = request.form.get('movie_imdb_id')
            year = request.form.get('movie_release_year')
            genre = request.form.get('movie_genre')
            m_type = request.form.get('movie_type')
            image_url = request.form.get('movie_image_url')
            user_token = current_user.token


            new_movie = Movie(
                title=title, 
                imdb_id=imdb_id, 
                release_year=year,
                genre=genre,
                m_type=m_type,
                image_url=image_url,
                user_token=user_token
            )

            print(f"Movie data= {new_movie}")

            db.session.add(new_movie)
            db.session.commit()


            current_user_token = current_user.token

            mov = Movie.query.filter_by(user_token=current_user_token).all()

            
            return render_template('watchlist.html', movies=mov)

        except:
            raise Exception("Movie not added, please check your form and try again!")

@site.route('/watchlist')
@login_required
def watchlist():
    
    current_user_token = current_user.token

    movies = Movie.query.filter_by(user_token=current_user_token).all()
   
    return render_template('watchlist.html', movies=movies)


@site.route('/delete', methods=['GET', 'POST'])
@login_required
def delete_movie():
    movie_id = request.form.get('movie_id')
    movie = Movie.query.get(movie_id)

    if movie:
        db.session.delete(movie)
        db.session.commit()

        return redirect('/watchlist')
    
    else:
        return "Movie not found"

movie/templates/base.html
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title>MovieHunter</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="../static/css/main.css" type="text/css" media="all" />
    <script type="text/javascript" src="../static/js/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="../static/js/jquery-func.js"></script>
    <!--[if IE 6]><link rel="stylesheet" href="css/ie6.css" type="text/css" media="all" /><![endif]-->
</head>

<body>
    <!-- START PAGE SOURCE -->
    <div id="shell">
        <div id="header">
            <h1 id="logo"><a href="#">MovieHunter</a></h1>
            <div class="social"> <span>FOLLOW US ON:</span>
                <ul>
                    <li><a class="twitter" href="#">twitter</a></li>
                    <li><a class="facebook" href="#">facebook</a></li>
                    <li><a class="vimeo" href="#">vimeo</a></li>
                    <li><a class="rss" href="#">rss</a></li>
                </ul>
            </div>
            <div id="navigation">
                <ul>
                <li><a href="{{ url_for('site.home') }}">Home</a></li>
                
                {% if current_user.is_authenticated %}
                
                <li><a href="{{ url_for('site.search_movies') }}">Search Movie</li>
                <li><a href="{{ url_for('site.watchlist') }}">Watch List</li>
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                
                {% else %}

                <li><a href="{{ url_for('auth.signin') }}">Sign In</a></li>
                <li><a href="{{ url_for('auth.signup') }}">Sign Up</a></li>
                
                {% endif %}
                </ul>
            </div>
            <div id="sub-navigation">
            </div>
        </div>
        <div id="main">

        


            {% block content %}
            <!-- other content lives here -->
            {% endblock content %}




            <div class="cl">&nbsp;</div>
        </div>

        <div id="footer">
            <p class="lf">Enjoy Watching here</p>
            <div style="clear:both;"></div>
        </div>
    </div>
    <!-- END PAGE SOURCE -->
</body>

</html>

movie/templates/signin_form.html
<form method="POST">

    {{ form.hidden_tag() }}
    <div class="form-group">

        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Please Username Here...") }}
        </fieldset>

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Please Email Here...") }}
        </fieldset>

        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Please Password Here...") }}
        </fieldset>

        <!-- Submit button -->
        <br>
        {{ form.submit_button(class="btn primary btn-block mt-2") }}

    </div>

</form>

movie/templates/signup_forms.html
<form method="POST">

    {{ form.hidden_tag() }}
    <div class="form-group">

        <fieldset id="firstname-field">
            {{ form.firstname.label }}
            {{ form.firstname(class="form-control", placeholder="Please enter your first name...") }}
        </fieldset>

        <fieldset id="lastname-field">
            {{ form.lastname.label }}
            {{ form.lastname(class="form-control", placeholder="Please enter your last name...") }}
        </fieldset>

        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class="form-control", placeholder="Please enter your username...") }}
        </fieldset>

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder="Please enter your email...") }}
        </fieldset>

        <fieldset id="dob-field">
            {{ form.date_of_birth.label }}
            {{ form.date_of_birth(class="form-control", placeholder="Please enter your date of birth (YYYY-MM-DD)...") }}
        </fieldset>

        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder="Please enter your password...") }}
        </fieldset>

        <!-- Submit button -->
        <br>
        {{ form.submit_button(class="btn primary btn-block mt-2") }}

    </div>

</form>